//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerTravell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration
    {
        public int ID_Quantri { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
    }
}
