//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerTravell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int MaLH { get; set; }
        public string HoTen { get; set; }
        public string ChucDanh { get; set; }
        public string CongTy { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string NoiDungLH { get; set; }
        public string TrangThai { get; set; }
    }
}
