//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerTravell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID_Tin { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string URL_hinh { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> ID_LoaiTin { get; set; }
        public Nullable<int> SoLanXem { get; set; }
        public Nullable<int> TinNoiBat { get; set; }
    }
}
