//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerTravell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.TourBookings = new HashSet<TourBooking>();
        }
    
        public int MaTour { get; set; }
        public string TenTour { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> SoDem { get; set; }
        public Nullable<int> SoCho { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public Nullable<int> TourHot { get; set; }
        public Nullable<int> MaTinh { get; set; }
    
        public virtual ProvinceCity ProvinceCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourBooking> TourBookings { get; set; }
    }
}
